[package]
name = "boytacean-common"
description = "Commons library for Boytacen."
version = "0.10.6"
authors = ["João Magalhães <joamag@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
pyo3 = { version = "0.20", optional = true }

[features]
python = ["pyo3"]
