[package]
name = "boytacean-encoding"
description = "Codecs library for Boytacen."
version = "0.10.9"
authors = ["João Magalhães <joamag@gmail.com>"]
license = "Apache-2.0"
edition = "2021"

[features]
simd = ["boytacean-hashing/simd"]

[dependencies]
boytacean-common = { path = "../common", version = "0.10.9" }
boytacean-hashing = { path = "../hashing", version = "0.10.9" }

[[bin]]
name = "zippy"
path = "src/cli/zippy.rs"
